# docker compose version (maybe adjust)
version: "3.8"

services:
  db:
    image: mongo
    restart: unless-stopped

    # port for mongodb only for testing
    ports:
      - "27018:27017"

    # TODO: Do we need networks-functionality?

    # mongodb depends on volume to keep the data alive
    volumes:
      - data:/data/db

    # environment variables
    # environment:
      # MONGO_INITDB_DATABASE: "admin"
      # MONGO_INITDB_ROOT_USERNAME: "admin"
      # MONGO_INITDB_ROOT_PASSWORD: "start"
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  backend:
    container_name: jobboard_backend
    # TODO: Do we need restart-functionality?
    image: jobboard-backend:1.0.0
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3080:3080 # Depends on what port is specified in backend
    depends_on:
      - db
    environment:
      MONGO_USERNAME: "admin"
      MONGO_PASSWORD: "start"
      MONGO_HOST: "mongodb"
      MONGO_PORT: "27018"
    volumes:
      - ./backend:/usr/src/backend # Mount the backend code directory
      - /usr/src/backend/node_modules/

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"  # Depends on what port is specified in frontend1
    volumes:
      - ./frontend:/usr/src/frontend  # Mount the frontend1 code directory
      - /usr/src/frontend/node_modules/

volumes:
  data:

# Run this file with 'docker-compose build' in same directory to build the whole application
# Then 'docker-compose up'


